### ISSUE TITLE
能问下你的背单词软件是什么么？

### ISSUE THREAD

**Issue by ishiguang** [byoungd/english-level-up-tips-for-chinese-programmers-and-designers#2]

**Comment by byoungd** [comment]
使用最多的：
1.有道词典（有Mac、iPhone、iPad、win全平台客户端，同步单词本比较方便，而且免费）
次多的：
2.扇贝单词（这个app我使用的时间并不长，因为平时的单词都是在学习、阅读、看视频时遇到的，每天午饭时我抽大约16分钟背一组单词，设定的目标是20个）

**Comment by iVanilla** [comment]
强烈推荐Anki！！！

**Comment by kn007** [comment]
我一会试试扇贝和Anki
