### ISSUE TITLE
所以你把整个教育阶段最重要的学科放弃了？

### ISSUE THREAD

**Issue by dandananddada** [byoungd/english-level-up-tips-for-chinese-programmers-and-designers#8]
古希腊有位哲学家说过：人与动物最大的区别就是对数的认知。

**Comment by byoungd** [comment]
到了大学有了新的认识嘛，不过丧失掉了最佳的学习时期。

这也是我为什么非常讨厌有些媒体鼓励辍学 

在最合适的时期做最合适的事，既然在春天就不要去做秋天的事。

**Comment by iVanilla** [comment]
数学吼蛙，理科大法好！ (
