### ISSUE TITLE
听力篇有声书配图文字和背景颜色一样

### ISSUE THREAD

**Issue by wr1241** [byoungd/english-level-up-tips-for-chinese-programmers-and-designers#9]
就是amazon audible那张[图](https://camo.githubusercontent.com/1a174da70dd5a13bc46ce9676982c0e119474d48/68747470733a2f2f6d2e6d656469612d616d617a6f6e2e636f6d2f696d616765732f472f30312f41756469626c652f656e5f55532f696d616765732f63726561746976652f6c616e64696e672f41756469626c655f4c6f676f5f57686974652e737667)，文字是白色的，背景也是白色的。

**Comment by byoungd** [comment]
感谢
